project:
  type: website
  output-dir: docs

website:
  title: "lizwebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: cv.qmd
        text: CV
      - href: posts.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

